version: '3.9' 
services:
  prodapp-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=prod_db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  
  myapp-main:
    build: .
    restart: always
    depends_on:
      - prodapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=prodapp-mysql
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=prod_db
      - DATABASE_PORT=3306

volumes:
   mysql_data:
   
